// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCalendar: typeof import('element-plus/es')['ElCalendar']
  const ElCas: typeof import('element-plus/es')['ElCas']
  const ElCascader: typeof import('element-plus/es')['ElCascader']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElElCalendar: typeof import('element-plus/es')['ElElCalendar']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElProgress: typeof import('element-plus/es')['ElProgress']
}
export {}
