// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/avatar/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElElCalendar: typeof import('element-plus/es')['ElElCalendar']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    HistoryItem: typeof import('./src/components/home-history/history-item.vue')['default']
    HomeBookList: typeof import('./src/components/home-book-list.vue')['default']
    HomeCate: typeof import('./src/components/HomeCate.vue')['default']
    HomeHistory: typeof import('./src/components/home-history/index.vue')['default']
    HomePoster: typeof import('./src/components/HomePoster.vue')['default']
    Rate: typeof import('./src/components/Rate.vue')['default']
    Result: typeof import('./src/components/search/Result.vue')['default']
    Search: typeof import('./src/components/search/index.vue')['default']
    SearchHistory: typeof import('./src/components/search/SearchHistory.vue')['default']
    UploadFile: typeof import('./src/components/upload-file/index.vue')['default']
    UserPanel: typeof import('./src/components/avatar/user-panel.vue')['default']
  }
}

export { }
